### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by dwlsalmeida** [briankendall/vscode-indent-to-bracket#3]
Does not show up in the marketplace, nor provides a vsix file.

**Comment by briankendall** [comment]
I've provided vsix files in the project's releases. [Here's the latest as of me writing this.](https://github.com/briankendall/vscode-indent-to-bracket/releases/tag/v1.0.1)

**Comment by dwlsalmeida** [comment]
very well sir, you got me. 

Thank you & Happy holidays...
